.Dd October 09, 2020
.Dt COMPRESS 1
.Os Dennix
.Sh NAME
.Nm compress ,
.Nm uncompress ,
.Nm zcat
.Nd compress and decompress data
.Sh SYNOPSIS
.Nm
.Op Fl 123456789cdfghlOrtvV
.Op Fl b Ar level
.Op Fl m Ar algo
.Op Fl o Ar filename
.Op Ar files...
.Nm uncompress
.Op Fl cflrtv
.Op Fl o Ar filename
.Op Ar files...
.Nm zcat
.Op Fl rv
.Op Ar files...
.Sh DESCRIPTION
The
.Nm
utility compresses or decompresses files.
Multiple compression algorithms are supported.
.Pp
When compressing, each operand is taken as an input file to be compressed.
When an operand is named
.Cm - ,
or if no operands are given, the standard input is used as the input file and
the compressed data is written to the standard output.
Unless the
.Fl c
option is specified, the compressed output is written into a file named like the
input file but with the suffix associated to the algorithm appended.
If the compression does not result in a size reduction and the
.Fl f
option is not given, the output file is unlinked and the input file is not
unlinked.
Otherwise, the input file is unlinked.
.Pp
The following compression algorithms are supported and can be selected using the
.Fl m
option:
.Bl -tag -width Ds
.It Cm lzw
The Lempel-Ziv-Welch (LZW) algorithm.
The suffix associated with this algorithm is
.Pa .Z .
Additionally when decompressing, the suffix
.Pa .taz
is supported which will be replaced by
.Pa .tar
to produce the output file name.
This algorithm is used by default.
.It Cm deflate
The DEFLATE (gzip) algorithm.
The suffix associated with this algorithm is
.Pa .gz .
Additionally when decompressing, the suffix
.Pa .tgz
is supported which will be replaced by
.Pa .tar
to produce the output file name.
.It Cm gzip
Synonym for
.Cm deflate .
.El
.Pp
When decompressing
.Pq Fl d ,
each operand is taken as an input file to be decompressed.
When an operand is named
.Cm - ,
or if no operands are given, the standard input is used as the input file and
the decompressed data is written to the standard output.
If an operand has no suffix associated with a supported algorithm, or if no file
named by the operand exists and the operand does not end with
.Pa .Z ,
the suffix
.Pa .Z
is appended to the operand and the resulting name is used as the input file.
Unless the
.Fl c
option is specified, the algorithm used for decompression is the one associated
with the suffix of the input file.
When the
.Fl c
option is specified, the algorithm is instead determined by the file contents.
.Pp
The
.Nm uncompress
utility is used for decompression only and is equivalent to
.Nm
.Fl d .
The
.Nm zcat
utility decompresses files to the standard output and is equivalent to
.Nm
.Fl cd .
Both
.Nm uncompress
and
.Nm zcat
support all options supported by
.Nm ,
but any options that do not make sense for decompression will be ignored.
.Pp
The following options are supported by
.Nm :
.Bl -tag -width Ds
.It Fl 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9
Set the compression level to the number given.
These options are equivalent to use of the
.Fl b
option with the number given as an option argument, except that the DEFLATE
(gzip) algorithm is used if no compression algorithm was selected explicitly
using the
.Fl g , m
or
.Fl O
options.
.It Fl b Ar level
Set the compression level.
The meaning depends on the compression algorithm used.
Usually a higher
.Ar level
achieves higher compression but might be slower.
For the LZW algorithm,
.Ar level
specifies the maximum number of bits to use in a code.
The values must be between 9 and 16 inclusive.
For the DEFLATE algorithm,
.Ar level
must be between 1 and 9 inclusive.
.It Fl c , -stdout , -to-stdout
Write the result of compression or decompression to the standard output and do
not unlink the input files.
For decompression, when the
.Fl c
option is used the algorithm is determined only by the file contents, not by the
file extension.
.It Fl d , -decompress , -uncompress
Decompress files instead of compressing them.
Unless the
.Fl c
option is also given, the algorithm to use for decompression is determined by
the file extension.
.It Fl f , -force
Always produce an output file even if compression does not result in a reduced
size.
Also overwrite existing output files without asking for confirmation.
.Pp
When used with the
.Fl c
and
.Fl d
options, any files that are not in a recognized format are written to the
standard output without change.
.It Fl g
Use the DEFLATE (gzip) algorithm for compression.
Equivalent to
.Fl m Cm gzip .
.It Fl h , -help
Print a short help message and exit.
.It Fl l , -list
List information about compressed files.
The following information is listed:
.Bl -tag -width "uncompressed name"
.It compressed
The size of the compressed file.
.It uncompressed
The size of the uncompressed file.
.It ratio
The compression ratio by which the size of the file was reduced.
.It uncompressed name
The name that will be used for the output file when decompressing.
.El
.Pp
If the
.Fl v
option is specified, the following additional information is printed in front of
the information above:
.Bl -tag -width "uncompressed name"
.It method
The algorithm that was used for compression.
This value is suitable for use as an argument to the
.Fl m
option.
.It crc
The 32-bit CRC (cyclic redundancy code) of the uncompressed data, if it is saved
within the compressed file.
For algorithms (like LZW) that do not save a CRC, this value is printed as
ffffffff.
.It date , time
The modification date and time of the compressed file.
.El
.It Fl m Ar algo
For compression use the compression algorithm specified by
.Ar algo .
.It Fl o Ar filename
Use
.Ar filename
as the output file name.
This option cannot be used with multiple input files or with any of the
.Fl clrt
options.
.It Fl O
Use the Lempel-Ziv-Welch (LZW) algorithm for compression.
Equivalent to
.Fl m Cm lzw .
.It Fl r , -recursive
Recursively compress or decompress directories.
For any given operand that names a directory, all files in that directory are
compressed or decompressed.
If a file in a directory already has the file extension associated with the used
algorithm, that file will be ignored.
.It Fl t , -test
Test the integrity of compressed files without changing any files.
.It Fl v , -verbose
For each file print the size reduction or expansion of the file.
.It Fl V , -version
Print version information and exit.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 if all input files were successfully compressed or decompressed.
It exits 1 or >2 when an error occured.
It exits 2 when at least one files was not compressed because compression would
have resulted in an increase of size.
.Pp
.Ex -std uncompress zcat
.Sh SEE ALSO
.Xr gzip 1 ,
.Xr tar 1
.Sh STANDARDS
The
.St -p1003.1-2008
standard specifies the
.Nm ,
.Nm uncompress
and
.Nm zcat
utilities as part of the XSI option.
Only the
.Fl bcfv
options and the Lempel-Ziv-Welch algorithm with between 9 and 14 bits per code
are standardized.
.Pp
The next revision of the POSIX.1 standard will additionally standardize the
.Fl dgm
options, add the DEFLATE algorithm and allow 15 and 16 bits per code for the LZW
algorithm.
.Pp
All other options are extensions to the standard.
.Pp
The DEFLATE compression algorithm and the gzip file format are standardized in
RFC1951 and RFC1952.
.Sh HISTORY
The
.Nm
utility was first implemented by
.An Spencer Thomas
in 1984.
The first
.Nm
implementation that supported the DEFLATE algorithm was the version that
appeared in
.Ox 2.1
in 1997.
.Pp
The implementation documented in this manual page began development in 2020 with
the goal of creating a modern
.Nm
implementation that conforms to the new requirements of POSIX.1-202x draft 1.
